-- Demo user seed data: 30 days of fitness history for user_id=6
-- Run: mysql -u root -proot fitlife < seed_demo.sql

SET @uid = 6;

-- ===================== WORKOUTS (30 days, ~1-2 per day, some rest days) =====================
INSERT INTO workouts (user_id, exercise_name, exercise_type, sets, reps, weight_lbs, duration_min, distance_km, notes, calories_burned, date) VALUES
(@uid, 'Bench Press', 'Strength', 4, 10, 135, NULL, NULL, 'Felt strong', 180, DATE_SUB(NOW(), INTERVAL 30 DAY)),
(@uid, 'Running', 'Cardio', NULL, NULL, NULL, 30, 4.5, 'Morning jog', 320, DATE_SUB(NOW(), INTERVAL 30 DAY)),
(@uid, 'Squats', 'Strength', 4, 12, 185, NULL, NULL, '', 220, DATE_SUB(NOW(), INTERVAL 29 DAY)),
(@uid, 'Plank', 'Flexibility', NULL, NULL, NULL, 10, NULL, 'Core day', 60, DATE_SUB(NOW(), INTERVAL 29 DAY)),
(@uid, 'Cycling', 'Cardio', NULL, NULL, NULL, 45, 15, 'Outdoor ride', 400, DATE_SUB(NOW(), INTERVAL 28 DAY)),
(@uid, 'Deadlift', 'Strength', 3, 8, 225, NULL, NULL, '', 250, DATE_SUB(NOW(), INTERVAL 27 DAY)),
(@uid, 'Pull Ups', 'Strength', 4, 8, NULL, NULL, NULL, 'Bodyweight', 150, DATE_SUB(NOW(), INTERVAL 27 DAY)),
(@uid, 'Yoga', 'Flexibility', NULL, NULL, NULL, 40, NULL, 'Rest & stretch', 120, DATE_SUB(NOW(), INTERVAL 26 DAY)),
(@uid, 'HIIT Circuit', 'HIIT', 5, 15, NULL, 25, NULL, 'Intense session', 350, DATE_SUB(NOW(), INTERVAL 25 DAY)),
(@uid, 'Running', 'Cardio', NULL, NULL, NULL, 35, 5.2, 'Longer run', 380, DATE_SUB(NOW(), INTERVAL 24 DAY)),
(@uid, 'Bench Press', 'Strength', 4, 8, 145, NULL, NULL, 'Increased weight', 190, DATE_SUB(NOW(), INTERVAL 23 DAY)),
(@uid, 'Shoulder Press', 'Strength', 3, 10, 95, NULL, NULL, '', 140, DATE_SUB(NOW(), INTERVAL 23 DAY)),
(@uid, 'Swimming', 'Cardio', NULL, NULL, NULL, 40, 1.5, 'Pool session', 350, DATE_SUB(NOW(), INTERVAL 22 DAY)),
-- rest day 21
(@uid, 'Squats', 'Strength', 4, 10, 195, NULL, NULL, 'PR attempt', 240, DATE_SUB(NOW(), INTERVAL 20 DAY)),
(@uid, 'Lunges', 'Strength', 3, 12, 80, NULL, NULL, '', 160, DATE_SUB(NOW(), INTERVAL 20 DAY)),
(@uid, 'Running', 'Cardio', NULL, NULL, NULL, 25, 3.8, 'Easy pace', 280, DATE_SUB(NOW(), INTERVAL 19 DAY)),
(@uid, 'HIIT Circuit', 'HIIT', 4, 20, NULL, 30, NULL, 'Burpees & jumps', 380, DATE_SUB(NOW(), INTERVAL 18 DAY)),
(@uid, 'Deadlift', 'Strength', 4, 6, 245, NULL, NULL, 'Heavy day', 270, DATE_SUB(NOW(), INTERVAL 17 DAY)),
(@uid, 'Cycling', 'Cardio', NULL, NULL, NULL, 50, 18, 'Long ride', 450, DATE_SUB(NOW(), INTERVAL 16 DAY)),
(@uid, 'Yoga', 'Flexibility', NULL, NULL, NULL, 35, NULL, 'Recovery', 100, DATE_SUB(NOW(), INTERVAL 15 DAY)),
-- rest day 14
(@uid, 'Bench Press', 'Strength', 4, 10, 150, NULL, NULL, 'New PR!', 200, DATE_SUB(NOW(), INTERVAL 13 DAY)),
(@uid, 'Rows', 'Strength', 3, 10, 115, NULL, NULL, '', 160, DATE_SUB(NOW(), INTERVAL 13 DAY)),
(@uid, 'Running', 'Cardio', NULL, NULL, NULL, 40, 6.0, 'Tempo run', 420, DATE_SUB(NOW(), INTERVAL 12 DAY)),
(@uid, 'HIIT Circuit', 'HIIT', 5, 12, NULL, 20, NULL, 'Quick blast', 300, DATE_SUB(NOW(), INTERVAL 11 DAY)),
(@uid, 'Squats', 'Strength', 5, 8, 205, NULL, NULL, 'Strength gains', 260, DATE_SUB(NOW(), INTERVAL 10 DAY)),
(@uid, 'Basketball', 'Sports', NULL, NULL, NULL, 60, NULL, 'Pickup game', 500, DATE_SUB(NOW(), INTERVAL 9 DAY)),
(@uid, 'Swimming', 'Cardio', NULL, NULL, NULL, 35, 1.2, '', 300, DATE_SUB(NOW(), INTERVAL 8 DAY)),
-- rest day 7
(@uid, 'Deadlift', 'Strength', 4, 8, 235, NULL, NULL, '', 260, DATE_SUB(NOW(), INTERVAL 6 DAY)),
(@uid, 'Pull Ups', 'Strength', 5, 10, NULL, NULL, NULL, 'Improving!', 170, DATE_SUB(NOW(), INTERVAL 6 DAY)),
(@uid, 'Running', 'Cardio', NULL, NULL, NULL, 30, 4.8, 'Morning run', 340, DATE_SUB(NOW(), INTERVAL 5 DAY)),
(@uid, 'HIIT Circuit', 'HIIT', 5, 15, NULL, 25, NULL, '', 360, DATE_SUB(NOW(), INTERVAL 4 DAY)),
(@uid, 'Bench Press', 'Strength', 4, 10, 155, NULL, NULL, 'Consistent', 210, DATE_SUB(NOW(), INTERVAL 3 DAY)),
(@uid, 'Cycling', 'Cardio', NULL, NULL, NULL, 40, 14, 'Weekend ride', 380, DATE_SUB(NOW(), INTERVAL 2 DAY)),
(@uid, 'Yoga', 'Flexibility', NULL, NULL, NULL, 30, NULL, 'Sunday stretch', 90, DATE_SUB(NOW(), INTERVAL 1 DAY)),
(@uid, 'Running', 'Cardio', NULL, NULL, NULL, 28, 4.2, 'Today', 310, NOW());

-- ===================== MEALS (30 days, 3 meals/day) =====================
INSERT INTO meals (user_id, food_name, meal_type, quantity, unit, calories, protein, carbs, fat, date) VALUES
-- Day 30
(@uid, 'Oatmeal with Banana', 'Breakfast', 300, 'g', 350, 12, 55, 8, DATE_SUB(NOW(), INTERVAL 30 DAY)),
(@uid, 'Chicken Breast & Rice', 'Lunch', 400, 'g', 520, 42, 55, 10, DATE_SUB(NOW(), INTERVAL 30 DAY)),
(@uid, 'Salmon with Veggies', 'Dinner', 350, 'g', 480, 35, 20, 22, DATE_SUB(NOW(), INTERVAL 30 DAY)),
-- Day 29
(@uid, 'Greek Yogurt & Almonds', 'Breakfast', 250, 'g', 320, 22, 18, 16, DATE_SUB(NOW(), INTERVAL 29 DAY)),
(@uid, 'Turkey Sandwich', 'Lunch', 300, 'g', 450, 30, 40, 15, DATE_SUB(NOW(), INTERVAL 29 DAY)),
(@uid, 'Steak & Sweet Potato', 'Dinner', 400, 'g', 620, 40, 45, 24, DATE_SUB(NOW(), INTERVAL 29 DAY)),
-- Day 28
(@uid, 'Eggs & Toast', 'Breakfast', 250, 'g', 380, 22, 30, 18, DATE_SUB(NOW(), INTERVAL 28 DAY)),
(@uid, 'Pasta with Chicken', 'Lunch', 350, 'g', 550, 35, 60, 14, DATE_SUB(NOW(), INTERVAL 28 DAY)),
(@uid, 'Grilled Fish & Salad', 'Dinner', 300, 'g', 400, 38, 15, 16, DATE_SUB(NOW(), INTERVAL 28 DAY)),
-- Day 27
(@uid, 'Protein Shake & Banana', 'Breakfast', 400, 'ml', 310, 30, 35, 5, DATE_SUB(NOW(), INTERVAL 27 DAY)),
(@uid, 'Chicken Wrap', 'Lunch', 300, 'g', 480, 32, 42, 16, DATE_SUB(NOW(), INTERVAL 27 DAY)),
(@uid, 'Brown Rice & Veggies', 'Dinner', 350, 'g', 420, 15, 65, 10, DATE_SUB(NOW(), INTERVAL 27 DAY)),
-- Day 26
(@uid, 'Oatmeal with Berries', 'Breakfast', 300, 'g', 340, 10, 52, 9, DATE_SUB(NOW(), INTERVAL 26 DAY)),
(@uid, 'Salmon Salad', 'Lunch', 350, 'g', 460, 34, 18, 25, DATE_SUB(NOW(), INTERVAL 26 DAY)),
(@uid, 'Chicken Stir Fry', 'Dinner', 400, 'g', 500, 38, 40, 16, DATE_SUB(NOW(), INTERVAL 26 DAY)),
-- Day 25
(@uid, 'Eggs & Avocado Toast', 'Breakfast', 280, 'g', 420, 20, 28, 26, DATE_SUB(NOW(), INTERVAL 25 DAY)),
(@uid, 'Turkey & Rice Bowl', 'Lunch', 380, 'g', 510, 36, 52, 12, DATE_SUB(NOW(), INTERVAL 25 DAY)),
(@uid, 'Cottage Cheese & Fruit', 'Dinner', 300, 'g', 320, 24, 30, 8, DATE_SUB(NOW(), INTERVAL 25 DAY)),
-- Day 24
(@uid, 'Pancakes & Syrup', 'Breakfast', 250, 'g', 450, 10, 65, 14, DATE_SUB(NOW(), INTERVAL 24 DAY)),
(@uid, 'Grilled Chicken Salad', 'Lunch', 350, 'g', 380, 35, 15, 18, DATE_SUB(NOW(), INTERVAL 24 DAY)),
(@uid, 'Pasta Bolognese', 'Dinner', 400, 'g', 580, 28, 65, 20, DATE_SUB(NOW(), INTERVAL 24 DAY)),
-- Day 23
(@uid, 'Greek Yogurt & Granola', 'Breakfast', 300, 'g', 360, 18, 42, 12, DATE_SUB(NOW(), INTERVAL 23 DAY)),
(@uid, 'Chicken Breast & Broccoli', 'Lunch', 350, 'g', 420, 40, 20, 12, DATE_SUB(NOW(), INTERVAL 23 DAY)),
(@uid, 'Salmon & Quinoa', 'Dinner', 380, 'g', 520, 36, 40, 20, DATE_SUB(NOW(), INTERVAL 23 DAY)),
-- Day 22
(@uid, 'Peanut Butter Toast', 'Breakfast', 200, 'g', 380, 14, 32, 22, DATE_SUB(NOW(), INTERVAL 22 DAY)),
(@uid, 'Beef Stir Fry', 'Lunch', 400, 'g', 540, 32, 45, 22, DATE_SUB(NOW(), INTERVAL 22 DAY)),
(@uid, 'Grilled Veggies & Hummus', 'Dinner', 350, 'g', 350, 12, 40, 15, DATE_SUB(NOW(), INTERVAL 22 DAY)),
-- Day 21 (rest day - lighter eating)
(@uid, 'Cereal & Milk', 'Breakfast', 300, 'g', 300, 10, 50, 6, DATE_SUB(NOW(), INTERVAL 21 DAY)),
(@uid, 'Tuna Sandwich', 'Lunch', 280, 'g', 420, 30, 35, 14, DATE_SUB(NOW(), INTERVAL 21 DAY)),
(@uid, 'Soup & Bread', 'Dinner', 400, 'g', 380, 15, 50, 10, DATE_SUB(NOW(), INTERVAL 21 DAY)),
-- Day 20
(@uid, 'Oatmeal & Protein Shake', 'Breakfast', 350, 'g', 410, 28, 48, 10, DATE_SUB(NOW(), INTERVAL 20 DAY)),
(@uid, 'Chicken Caesar Salad', 'Lunch', 350, 'g', 450, 34, 20, 24, DATE_SUB(NOW(), INTERVAL 20 DAY)),
(@uid, 'Steak & Veggies', 'Dinner', 400, 'g', 560, 42, 18, 28, DATE_SUB(NOW(), INTERVAL 20 DAY)),
-- Day 19
(@uid, 'Eggs Benedict', 'Breakfast', 300, 'g', 440, 22, 30, 26, DATE_SUB(NOW(), INTERVAL 19 DAY)),
(@uid, 'Chicken & Sweet Potato', 'Lunch', 380, 'g', 490, 36, 50, 10, DATE_SUB(NOW(), INTERVAL 19 DAY)),
(@uid, 'Fish Tacos', 'Dinner', 350, 'g', 480, 28, 42, 18, DATE_SUB(NOW(), INTERVAL 19 DAY)),
-- Day 18
(@uid, 'Smoothie Bowl', 'Breakfast', 350, 'g', 380, 15, 55, 10, DATE_SUB(NOW(), INTERVAL 18 DAY)),
(@uid, 'Beef Burrito Bowl', 'Lunch', 400, 'g', 580, 30, 60, 20, DATE_SUB(NOW(), INTERVAL 18 DAY)),
(@uid, 'Grilled Chicken & Rice', 'Dinner', 380, 'g', 500, 38, 50, 12, DATE_SUB(NOW(), INTERVAL 18 DAY)),
-- Day 17
(@uid, 'Oatmeal with Nuts', 'Breakfast', 300, 'g', 390, 14, 45, 16, DATE_SUB(NOW(), INTERVAL 17 DAY)),
(@uid, 'Salmon Bowl', 'Lunch', 380, 'g', 510, 32, 42, 20, DATE_SUB(NOW(), INTERVAL 17 DAY)),
(@uid, 'Turkey Meatballs & Pasta', 'Dinner', 400, 'g', 540, 34, 55, 16, DATE_SUB(NOW(), INTERVAL 17 DAY)),
-- Day 16
(@uid, 'Greek Yogurt & Honey', 'Breakfast', 250, 'g', 280, 18, 35, 6, DATE_SUB(NOW(), INTERVAL 16 DAY)),
(@uid, 'Chicken Quesadilla', 'Lunch', 300, 'g', 520, 28, 40, 24, DATE_SUB(NOW(), INTERVAL 16 DAY)),
(@uid, 'Shrimp & Veggies', 'Dinner', 350, 'g', 380, 32, 20, 14, DATE_SUB(NOW(), INTERVAL 16 DAY)),
-- Day 15
(@uid, 'Banana Protein Pancakes', 'Breakfast', 280, 'g', 400, 24, 42, 14, DATE_SUB(NOW(), INTERVAL 15 DAY)),
(@uid, 'Grilled Chicken Wrap', 'Lunch', 320, 'g', 460, 32, 38, 16, DATE_SUB(NOW(), INTERVAL 15 DAY)),
(@uid, 'Salmon & Asparagus', 'Dinner', 350, 'g', 470, 36, 15, 24, DATE_SUB(NOW(), INTERVAL 15 DAY)),
-- Day 14 (rest day)
(@uid, 'Avocado Toast', 'Breakfast', 200, 'g', 340, 10, 28, 20, DATE_SUB(NOW(), INTERVAL 14 DAY)),
(@uid, 'Veggie Soup', 'Lunch', 400, 'g', 280, 10, 40, 8, DATE_SUB(NOW(), INTERVAL 14 DAY)),
(@uid, 'Pizza (2 slices)', 'Dinner', 300, 'g', 560, 20, 55, 24, DATE_SUB(NOW(), INTERVAL 14 DAY)),
-- Day 13
(@uid, 'Eggs & Bacon', 'Breakfast', 250, 'g', 420, 26, 5, 32, DATE_SUB(NOW(), INTERVAL 13 DAY)),
(@uid, 'Chicken & Brown Rice', 'Lunch', 400, 'g', 520, 40, 52, 12, DATE_SUB(NOW(), INTERVAL 13 DAY)),
(@uid, 'Grilled Steak Salad', 'Dinner', 380, 'g', 500, 38, 15, 28, DATE_SUB(NOW(), INTERVAL 13 DAY)),
-- Day 12
(@uid, 'Protein Shake', 'Breakfast', 400, 'ml', 280, 30, 20, 6, DATE_SUB(NOW(), INTERVAL 12 DAY)),
(@uid, 'Tuna Poke Bowl', 'Lunch', 350, 'g', 460, 34, 45, 14, DATE_SUB(NOW(), INTERVAL 12 DAY)),
(@uid, 'Chicken Parmesan', 'Dinner', 380, 'g', 580, 36, 40, 26, DATE_SUB(NOW(), INTERVAL 12 DAY)),
-- Day 11
(@uid, 'Oatmeal & Blueberries', 'Breakfast', 300, 'g', 330, 10, 52, 8, DATE_SUB(NOW(), INTERVAL 11 DAY)),
(@uid, 'Turkey Burger', 'Lunch', 300, 'g', 480, 32, 35, 20, DATE_SUB(NOW(), INTERVAL 11 DAY)),
(@uid, 'Salmon & Sweet Potato', 'Dinner', 380, 'g', 510, 34, 42, 18, DATE_SUB(NOW(), INTERVAL 11 DAY)),
-- Day 10
(@uid, 'Eggs & Oatmeal', 'Breakfast', 300, 'g', 400, 22, 42, 14, DATE_SUB(NOW(), INTERVAL 10 DAY)),
(@uid, 'Chicken Teriyaki Bowl', 'Lunch', 400, 'g', 540, 34, 58, 14, DATE_SUB(NOW(), INTERVAL 10 DAY)),
(@uid, 'Lean Beef & Broccoli', 'Dinner', 380, 'g', 480, 36, 20, 24, DATE_SUB(NOW(), INTERVAL 10 DAY)),
-- Day 9
(@uid, 'French Toast', 'Breakfast', 250, 'g', 420, 14, 50, 18, DATE_SUB(NOW(), INTERVAL 9 DAY)),
(@uid, 'Chicken Burrito', 'Lunch', 380, 'g', 560, 30, 55, 22, DATE_SUB(NOW(), INTERVAL 9 DAY)),
(@uid, 'Grilled Fish & Rice', 'Dinner', 350, 'g', 440, 34, 45, 12, DATE_SUB(NOW(), INTERVAL 9 DAY)),
-- Day 8
(@uid, 'Yogurt Parfait', 'Breakfast', 300, 'g', 350, 16, 45, 10, DATE_SUB(NOW(), INTERVAL 8 DAY)),
(@uid, 'Steak Fajitas', 'Lunch', 400, 'g', 540, 34, 40, 24, DATE_SUB(NOW(), INTERVAL 8 DAY)),
(@uid, 'Chicken Soup', 'Dinner', 400, 'g', 380, 28, 35, 12, DATE_SUB(NOW(), INTERVAL 8 DAY)),
-- Day 7 (rest day)
(@uid, 'Cereal & Banana', 'Breakfast', 300, 'g', 320, 8, 55, 6, DATE_SUB(NOW(), INTERVAL 7 DAY)),
(@uid, 'Ham & Cheese Sandwich', 'Lunch', 280, 'g', 440, 24, 38, 18, DATE_SUB(NOW(), INTERVAL 7 DAY)),
(@uid, 'Pasta Alfredo', 'Dinner', 380, 'g', 600, 22, 60, 28, DATE_SUB(NOW(), INTERVAL 7 DAY)),
-- Day 6
(@uid, 'Oatmeal & Peanut Butter', 'Breakfast', 300, 'g', 420, 16, 48, 18, DATE_SUB(NOW(), INTERVAL 6 DAY)),
(@uid, 'Chicken & Quinoa Bowl', 'Lunch', 380, 'g', 490, 38, 45, 14, DATE_SUB(NOW(), INTERVAL 6 DAY)),
(@uid, 'Salmon & Roasted Veggies', 'Dinner', 350, 'g', 480, 34, 22, 24, DATE_SUB(NOW(), INTERVAL 6 DAY)),
-- Day 5
(@uid, 'Scrambled Eggs & Toast', 'Breakfast', 280, 'g', 390, 24, 28, 18, DATE_SUB(NOW(), INTERVAL 5 DAY)),
(@uid, 'Grilled Chicken Wrap', 'Lunch', 320, 'g', 460, 34, 36, 16, DATE_SUB(NOW(), INTERVAL 5 DAY)),
(@uid, 'Beef Stew', 'Dinner', 400, 'g', 520, 32, 40, 22, DATE_SUB(NOW(), INTERVAL 5 DAY)),
-- Day 4
(@uid, 'Smoothie & Granola', 'Breakfast', 350, 'g', 380, 14, 52, 12, DATE_SUB(NOW(), INTERVAL 4 DAY)),
(@uid, 'Chicken Pesto Pasta', 'Lunch', 380, 'g', 560, 32, 55, 22, DATE_SUB(NOW(), INTERVAL 4 DAY)),
(@uid, 'Grilled Shrimp & Salad', 'Dinner', 320, 'g', 360, 30, 16, 18, DATE_SUB(NOW(), INTERVAL 4 DAY)),
-- Day 3
(@uid, 'Eggs & Sausage', 'Breakfast', 280, 'g', 440, 28, 8, 30, DATE_SUB(NOW(), INTERVAL 3 DAY)),
(@uid, 'Chicken & Rice', 'Lunch', 400, 'g', 500, 38, 50, 12, DATE_SUB(NOW(), INTERVAL 3 DAY)),
(@uid, 'Salmon Teriyaki', 'Dinner', 350, 'g', 490, 34, 35, 20, DATE_SUB(NOW(), INTERVAL 3 DAY)),
-- Day 2
(@uid, 'Protein Pancakes', 'Breakfast', 280, 'g', 400, 26, 38, 14, DATE_SUB(NOW(), INTERVAL 2 DAY)),
(@uid, 'Turkey Club Sandwich', 'Lunch', 320, 'g', 480, 30, 40, 18, DATE_SUB(NOW(), INTERVAL 2 DAY)),
(@uid, 'Chicken Tikka & Rice', 'Dinner', 400, 'g', 540, 34, 52, 18, DATE_SUB(NOW(), INTERVAL 2 DAY)),
-- Day 1
(@uid, 'Oatmeal & Berries', 'Breakfast', 300, 'g', 340, 12, 50, 8, DATE_SUB(NOW(), INTERVAL 1 DAY)),
(@uid, 'Chicken Caesar Wrap', 'Lunch', 320, 'g', 470, 32, 35, 20, DATE_SUB(NOW(), INTERVAL 1 DAY)),
(@uid, 'Steak & Mashed Potatoes', 'Dinner', 400, 'g', 580, 40, 40, 26, DATE_SUB(NOW(), INTERVAL 1 DAY)),
-- Today
(@uid, 'Greek Yogurt & Granola', 'Breakfast', 300, 'g', 360, 18, 42, 12, NOW()),
(@uid, 'Chicken Breast & Salad', 'Lunch', 350, 'g', 420, 38, 18, 14, NOW());

-- ===================== WATER LOGS (30 days, 4-8 entries per day) =====================
INSERT INTO water_logs (user_id, amount_ml, date, created_at) VALUES
(@uid, 500, DATE_SUB(CURDATE(), INTERVAL 30 DAY), DATE_SUB(NOW(), INTERVAL 30 DAY)),
(@uid, 330, DATE_SUB(CURDATE(), INTERVAL 30 DAY), DATE_SUB(NOW(), INTERVAL 30 DAY)),
(@uid, 500, DATE_SUB(CURDATE(), INTERVAL 30 DAY), DATE_SUB(NOW(), INTERVAL 30 DAY)),
(@uid, 250, DATE_SUB(CURDATE(), INTERVAL 30 DAY), DATE_SUB(NOW(), INTERVAL 30 DAY)),
(@uid, 500, DATE_SUB(CURDATE(), INTERVAL 30 DAY), DATE_SUB(NOW(), INTERVAL 30 DAY)),
(@uid, 500, DATE_SUB(CURDATE(), INTERVAL 29 DAY), DATE_SUB(NOW(), INTERVAL 29 DAY)),
(@uid, 330, DATE_SUB(CURDATE(), INTERVAL 29 DAY), DATE_SUB(NOW(), INTERVAL 29 DAY)),
(@uid, 500, DATE_SUB(CURDATE(), INTERVAL 29 DAY), DATE_SUB(NOW(), INTERVAL 29 DAY)),
(@uid, 500, DATE_SUB(CURDATE(), INTERVAL 29 DAY), DATE_SUB(NOW(), INTERVAL 29 DAY)),
(@uid, 750, DATE_SUB(CURDATE(), INTERVAL 28 DAY), DATE_SUB(NOW(), INTERVAL 28 DAY)),
(@uid, 500, DATE_SUB(CURDATE(), INTERVAL 28 DAY), DATE_SUB(NOW(), INTERVAL 28 DAY)),
(@uid, 500, DATE_SUB(CURDATE(), INTERVAL 28 DAY), DATE_SUB(NOW(), INTERVAL 28 DAY)),
(@uid, 330, DATE_SUB(CURDATE(), INTERVAL 28 DAY), DATE_SUB(NOW(), INTERVAL 28 DAY)),
(@uid, 500, DATE_SUB(CURDATE(), INTERVAL 27 DAY), DATE_SUB(NOW(), INTERVAL 27 DAY)),
(@uid, 500, DATE_SUB(CURDATE(), INTERVAL 27 DAY), DATE_SUB(NOW(), INTERVAL 27 DAY)),
(@uid, 330, DATE_SUB(CURDATE(), INTERVAL 27 DAY), DATE_SUB(NOW(), INTERVAL 27 DAY)),
(@uid, 250, DATE_SUB(CURDATE(), INTERVAL 27 DAY), DATE_SUB(NOW(), INTERVAL 27 DAY)),
(@uid, 500, DATE_SUB(CURDATE(), INTERVAL 26 DAY), DATE_SUB(NOW(), INTERVAL 26 DAY)),
(@uid, 500, DATE_SUB(CURDATE(), INTERVAL 26 DAY), DATE_SUB(NOW(), INTERVAL 26 DAY)),
(@uid, 750, DATE_SUB(CURDATE(), INTERVAL 26 DAY), DATE_SUB(NOW(), INTERVAL 26 DAY)),
(@uid, 500, DATE_SUB(CURDATE(), INTERVAL 25 DAY), DATE_SUB(NOW(), INTERVAL 25 DAY)),
(@uid, 330, DATE_SUB(CURDATE(), INTERVAL 25 DAY), DATE_SUB(NOW(), INTERVAL 25 DAY)),
(@uid, 500, DATE_SUB(CURDATE(), INTERVAL 25 DAY), DATE_SUB(NOW(), INTERVAL 25 DAY)),
(@uid, 500, DATE_SUB(CURDATE(), INTERVAL 25 DAY), DATE_SUB(NOW(), INTERVAL 25 DAY)),
(@uid, 500, DATE_SUB(CURDATE(), INTERVAL 24 DAY), DATE_SUB(NOW(), INTERVAL 24 DAY)),
(@uid, 500, DATE_SUB(CURDATE(), INTERVAL 24 DAY), DATE_SUB(NOW(), INTERVAL 24 DAY)),
(@uid, 330, DATE_SUB(CURDATE(), INTERVAL 24 DAY), DATE_SUB(NOW(), INTERVAL 24 DAY)),
(@uid, 500, DATE_SUB(CURDATE(), INTERVAL 23 DAY), DATE_SUB(NOW(), INTERVAL 23 DAY)),
(@uid, 750, DATE_SUB(CURDATE(), INTERVAL 23 DAY), DATE_SUB(NOW(), INTERVAL 23 DAY)),
(@uid, 500, DATE_SUB(CURDATE(), INTERVAL 23 DAY), DATE_SUB(NOW(), INTERVAL 23 DAY)),
(@uid, 330, DATE_SUB(CURDATE(), INTERVAL 22 DAY), DATE_SUB(NOW(), INTERVAL 22 DAY)),
(@uid, 500, DATE_SUB(CURDATE(), INTERVAL 22 DAY), DATE_SUB(NOW(), INTERVAL 22 DAY)),
(@uid, 500, DATE_SUB(CURDATE(), INTERVAL 22 DAY), DATE_SUB(NOW(), INTERVAL 22 DAY)),
(@uid, 250, DATE_SUB(CURDATE(), INTERVAL 21 DAY), DATE_SUB(NOW(), INTERVAL 21 DAY)),
(@uid, 500, DATE_SUB(CURDATE(), INTERVAL 21 DAY), DATE_SUB(NOW(), INTERVAL 21 DAY)),
(@uid, 330, DATE_SUB(CURDATE(), INTERVAL 21 DAY), DATE_SUB(NOW(), INTERVAL 21 DAY)),
(@uid, 500, DATE_SUB(CURDATE(), INTERVAL 20 DAY), DATE_SUB(NOW(), INTERVAL 20 DAY)),
(@uid, 500, DATE_SUB(CURDATE(), INTERVAL 20 DAY), DATE_SUB(NOW(), INTERVAL 20 DAY)),
(@uid, 750, DATE_SUB(CURDATE(), INTERVAL 20 DAY), DATE_SUB(NOW(), INTERVAL 20 DAY)),
(@uid, 330, DATE_SUB(CURDATE(), INTERVAL 20 DAY), DATE_SUB(NOW(), INTERVAL 20 DAY)),
(@uid, 500, DATE_SUB(CURDATE(), INTERVAL 19 DAY), DATE_SUB(NOW(), INTERVAL 19 DAY)),
(@uid, 500, DATE_SUB(CURDATE(), INTERVAL 19 DAY), DATE_SUB(NOW(), INTERVAL 19 DAY)),
(@uid, 330, DATE_SUB(CURDATE(), INTERVAL 19 DAY), DATE_SUB(NOW(), INTERVAL 19 DAY)),
(@uid, 500, DATE_SUB(CURDATE(), INTERVAL 18 DAY), DATE_SUB(NOW(), INTERVAL 18 DAY)),
(@uid, 500, DATE_SUB(CURDATE(), INTERVAL 18 DAY), DATE_SUB(NOW(), INTERVAL 18 DAY)),
(@uid, 500, DATE_SUB(CURDATE(), INTERVAL 18 DAY), DATE_SUB(NOW(), INTERVAL 18 DAY)),
(@uid, 250, DATE_SUB(CURDATE(), INTERVAL 18 DAY), DATE_SUB(NOW(), INTERVAL 18 DAY)),
(@uid, 500, DATE_SUB(CURDATE(), INTERVAL 17 DAY), DATE_SUB(NOW(), INTERVAL 17 DAY)),
(@uid, 330, DATE_SUB(CURDATE(), INTERVAL 17 DAY), DATE_SUB(NOW(), INTERVAL 17 DAY)),
(@uid, 750, DATE_SUB(CURDATE(), INTERVAL 17 DAY), DATE_SUB(NOW(), INTERVAL 17 DAY)),
(@uid, 500, DATE_SUB(CURDATE(), INTERVAL 16 DAY), DATE_SUB(NOW(), INTERVAL 16 DAY)),
(@uid, 500, DATE_SUB(CURDATE(), INTERVAL 16 DAY), DATE_SUB(NOW(), INTERVAL 16 DAY)),
(@uid, 330, DATE_SUB(CURDATE(), INTERVAL 16 DAY), DATE_SUB(NOW(), INTERVAL 16 DAY)),
(@uid, 500, DATE_SUB(CURDATE(), INTERVAL 16 DAY), DATE_SUB(NOW(), INTERVAL 16 DAY)),
(@uid, 500, DATE_SUB(CURDATE(), INTERVAL 15 DAY), DATE_SUB(NOW(), INTERVAL 15 DAY)),
(@uid, 500, DATE_SUB(CURDATE(), INTERVAL 15 DAY), DATE_SUB(NOW(), INTERVAL 15 DAY)),
(@uid, 330, DATE_SUB(CURDATE(), INTERVAL 15 DAY), DATE_SUB(NOW(), INTERVAL 15 DAY)),
(@uid, 250, DATE_SUB(CURDATE(), INTERVAL 14 DAY), DATE_SUB(NOW(), INTERVAL 14 DAY)),
(@uid, 330, DATE_SUB(CURDATE(), INTERVAL 14 DAY), DATE_SUB(NOW(), INTERVAL 14 DAY)),
(@uid, 500, DATE_SUB(CURDATE(), INTERVAL 14 DAY), DATE_SUB(NOW(), INTERVAL 14 DAY)),
(@uid, 500, DATE_SUB(CURDATE(), INTERVAL 13 DAY), DATE_SUB(NOW(), INTERVAL 13 DAY)),
(@uid, 750, DATE_SUB(CURDATE(), INTERVAL 13 DAY), DATE_SUB(NOW(), INTERVAL 13 DAY)),
(@uid, 500, DATE_SUB(CURDATE(), INTERVAL 13 DAY), DATE_SUB(NOW(), INTERVAL 13 DAY)),
(@uid, 330, DATE_SUB(CURDATE(), INTERVAL 13 DAY), DATE_SUB(NOW(), INTERVAL 13 DAY)),
(@uid, 500, DATE_SUB(CURDATE(), INTERVAL 12 DAY), DATE_SUB(NOW(), INTERVAL 12 DAY)),
(@uid, 500, DATE_SUB(CURDATE(), INTERVAL 12 DAY), DATE_SUB(NOW(), INTERVAL 12 DAY)),
(@uid, 500, DATE_SUB(CURDATE(), INTERVAL 12 DAY), DATE_SUB(NOW(), INTERVAL 12 DAY)),
(@uid, 500, DATE_SUB(CURDATE(), INTERVAL 11 DAY), DATE_SUB(NOW(), INTERVAL 11 DAY)),
(@uid, 330, DATE_SUB(CURDATE(), INTERVAL 11 DAY), DATE_SUB(NOW(), INTERVAL 11 DAY)),
(@uid, 500, DATE_SUB(CURDATE(), INTERVAL 11 DAY), DATE_SUB(NOW(), INTERVAL 11 DAY)),
(@uid, 750, DATE_SUB(CURDATE(), INTERVAL 11 DAY), DATE_SUB(NOW(), INTERVAL 11 DAY)),
(@uid, 500, DATE_SUB(CURDATE(), INTERVAL 10 DAY), DATE_SUB(NOW(), INTERVAL 10 DAY)),
(@uid, 500, DATE_SUB(CURDATE(), INTERVAL 10 DAY), DATE_SUB(NOW(), INTERVAL 10 DAY)),
(@uid, 330, DATE_SUB(CURDATE(), INTERVAL 10 DAY), DATE_SUB(NOW(), INTERVAL 10 DAY)),
(@uid, 500, DATE_SUB(CURDATE(), INTERVAL 9 DAY), DATE_SUB(NOW(), INTERVAL 9 DAY)),
(@uid, 500, DATE_SUB(CURDATE(), INTERVAL 9 DAY), DATE_SUB(NOW(), INTERVAL 9 DAY)),
(@uid, 500, DATE_SUB(CURDATE(), INTERVAL 9 DAY), DATE_SUB(NOW(), INTERVAL 9 DAY)),
(@uid, 330, DATE_SUB(CURDATE(), INTERVAL 9 DAY), DATE_SUB(NOW(), INTERVAL 9 DAY)),
(@uid, 500, DATE_SUB(CURDATE(), INTERVAL 8 DAY), DATE_SUB(NOW(), INTERVAL 8 DAY)),
(@uid, 500, DATE_SUB(CURDATE(), INTERVAL 8 DAY), DATE_SUB(NOW(), INTERVAL 8 DAY)),
(@uid, 750, DATE_SUB(CURDATE(), INTERVAL 8 DAY), DATE_SUB(NOW(), INTERVAL 8 DAY)),
(@uid, 250, DATE_SUB(CURDATE(), INTERVAL 7 DAY), DATE_SUB(NOW(), INTERVAL 7 DAY)),
(@uid, 500, DATE_SUB(CURDATE(), INTERVAL 7 DAY), DATE_SUB(NOW(), INTERVAL 7 DAY)),
(@uid, 330, DATE_SUB(CURDATE(), INTERVAL 7 DAY), DATE_SUB(NOW(), INTERVAL 7 DAY)),
(@uid, 500, DATE_SUB(CURDATE(), INTERVAL 6 DAY), DATE_SUB(NOW(), INTERVAL 6 DAY)),
(@uid, 500, DATE_SUB(CURDATE(), INTERVAL 6 DAY), DATE_SUB(NOW(), INTERVAL 6 DAY)),
(@uid, 750, DATE_SUB(CURDATE(), INTERVAL 6 DAY), DATE_SUB(NOW(), INTERVAL 6 DAY)),
(@uid, 330, DATE_SUB(CURDATE(), INTERVAL 6 DAY), DATE_SUB(NOW(), INTERVAL 6 DAY)),
(@uid, 500, DATE_SUB(CURDATE(), INTERVAL 5 DAY), DATE_SUB(NOW(), INTERVAL 5 DAY)),
(@uid, 500, DATE_SUB(CURDATE(), INTERVAL 5 DAY), DATE_SUB(NOW(), INTERVAL 5 DAY)),
(@uid, 500, DATE_SUB(CURDATE(), INTERVAL 5 DAY), DATE_SUB(NOW(), INTERVAL 5 DAY)),
(@uid, 500, DATE_SUB(CURDATE(), INTERVAL 4 DAY), DATE_SUB(NOW(), INTERVAL 4 DAY)),
(@uid, 330, DATE_SUB(CURDATE(), INTERVAL 4 DAY), DATE_SUB(NOW(), INTERVAL 4 DAY)),
(@uid, 500, DATE_SUB(CURDATE(), INTERVAL 4 DAY), DATE_SUB(NOW(), INTERVAL 4 DAY)),
(@uid, 500, DATE_SUB(CURDATE(), INTERVAL 4 DAY), DATE_SUB(NOW(), INTERVAL 4 DAY)),
(@uid, 500, DATE_SUB(CURDATE(), INTERVAL 3 DAY), DATE_SUB(NOW(), INTERVAL 3 DAY)),
(@uid, 500, DATE_SUB(CURDATE(), INTERVAL 3 DAY), DATE_SUB(NOW(), INTERVAL 3 DAY)),
(@uid, 750, DATE_SUB(CURDATE(), INTERVAL 3 DAY), DATE_SUB(NOW(), INTERVAL 3 DAY)),
(@uid, 500, DATE_SUB(CURDATE(), INTERVAL 2 DAY), DATE_SUB(NOW(), INTERVAL 2 DAY)),
(@uid, 330, DATE_SUB(CURDATE(), INTERVAL 2 DAY), DATE_SUB(NOW(), INTERVAL 2 DAY)),
(@uid, 500, DATE_SUB(CURDATE(), INTERVAL 2 DAY), DATE_SUB(NOW(), INTERVAL 2 DAY)),
(@uid, 500, DATE_SUB(CURDATE(), INTERVAL 1 DAY), DATE_SUB(NOW(), INTERVAL 1 DAY)),
(@uid, 500, DATE_SUB(CURDATE(), INTERVAL 1 DAY), DATE_SUB(NOW(), INTERVAL 1 DAY)),
(@uid, 750, DATE_SUB(CURDATE(), INTERVAL 1 DAY), DATE_SUB(NOW(), INTERVAL 1 DAY)),
(@uid, 330, DATE_SUB(CURDATE(), INTERVAL 1 DAY), DATE_SUB(NOW(), INTERVAL 1 DAY)),
(@uid, 500, CURDATE(), NOW()),
(@uid, 330, CURDATE(), NOW());

-- ===================== WEIGHT LOGS (every 2-3 days, gradual loss from 82 to 79.5) =====================
INSERT INTO weight_logs (user_id, weight_kg, date, notes, created_at) VALUES
(@uid, 82.0, DATE_SUB(CURDATE(), INTERVAL 30 DAY), 'Starting weight', DATE_SUB(NOW(), INTERVAL 30 DAY)),
(@uid, 81.8, DATE_SUB(CURDATE(), INTERVAL 27 DAY), '', DATE_SUB(NOW(), INTERVAL 27 DAY)),
(@uid, 81.5, DATE_SUB(CURDATE(), INTERVAL 24 DAY), 'Good progress', DATE_SUB(NOW(), INTERVAL 24 DAY)),
(@uid, 81.6, DATE_SUB(CURDATE(), INTERVAL 21 DAY), 'Small fluctuation', DATE_SUB(NOW(), INTERVAL 21 DAY)),
(@uid, 81.2, DATE_SUB(CURDATE(), INTERVAL 18 DAY), '', DATE_SUB(NOW(), INTERVAL 18 DAY)),
(@uid, 80.9, DATE_SUB(CURDATE(), INTERVAL 15 DAY), 'Halfway there', DATE_SUB(NOW(), INTERVAL 15 DAY)),
(@uid, 80.5, DATE_SUB(CURDATE(), INTERVAL 12 DAY), '', DATE_SUB(NOW(), INTERVAL 12 DAY)),
(@uid, 80.3, DATE_SUB(CURDATE(), INTERVAL 9 DAY), 'Feeling lighter', DATE_SUB(NOW(), INTERVAL 9 DAY)),
(@uid, 80.0, DATE_SUB(CURDATE(), INTERVAL 6 DAY), 'Hit 80!', DATE_SUB(NOW(), INTERVAL 6 DAY)),
(@uid, 79.8, DATE_SUB(CURDATE(), INTERVAL 3 DAY), 'Still going', DATE_SUB(NOW(), INTERVAL 3 DAY)),
(@uid, 79.5, CURDATE(), 'New low!', NOW());

-- ===================== GOALS =====================
INSERT INTO goals (user_id, title, type, target_value, current_value, unit, deadline, completed, created_at) VALUES
(@uid, 'Lose 5kg', 'weight', 77.0, 79.5, 'kg', DATE_ADD(CURDATE(), INTERVAL 45 DAY), false, DATE_SUB(NOW(), INTERVAL 30 DAY)),
(@uid, 'Run 50km this month', 'custom', 50.0, 38.5, 'km', DATE_ADD(CURDATE(), INTERVAL 15 DAY), false, DATE_SUB(NOW(), INTERVAL 15 DAY)),
(@uid, '30 workout sessions', 'workouts', 30.0, 22.0, 'sessions', DATE_ADD(CURDATE(), INTERVAL 20 DAY), false, DATE_SUB(NOW(), INTERVAL 30 DAY));

